add_newline = true
command_timeout = 1000

format = "$username$hostname$directory$git_branch$git_status$cmd_duration$line_break$character"

[username]
show_always = true
style_user = "bold cyan"
style_root = "bold red"

[hostname]
ssh_only = false
trim_at = "."
style = "bold dimmed blue"
format = "[@$hostname]($style) "

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold green"
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "yellow"
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
min_time = 2000
style = "bold yellow"
format = "took [$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
