name: Cleanup GHCR Images
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual execution

jobs:
  delete-old-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Obrigatório para deletar versões
    strategy:
      fail-fast: false
      matrix:
        image-name: [kinoite-amd, kinoite-nvidia] # Required to delete package versions
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.image-name }}
          package-type: 'container'
          min-versions-to-keep: 5 # Keeps the last 5 versions for safe rollback
          delete-only-untagged-versions: 'false' # Removes old tags as well
          # On GitHub, 'latest' is protected as it is not considered "old"